import { useQuery } from '@tanstack/react-query'
import { listRateLimits, updateRateLimit, deleteRateLimit } from '../api/ratelimit'
import { listQuotaPolicies, listQuotaUsage, deleteQuotaPolicy } from '../api/quota'
import { listPricing, deletePricing } from '../api/catalog'

export function UsagePage() { return <section className="panel"><h3>用量统计</h3><p className="muted">请使用用量统计页面查看完整数据。</p></section> }

export function LimitsPage() { const query = useQuery({ queryKey: ['rate-limits'], queryFn: listRateLimits }); return <section className="panel"><div className="panel-head"><h3>限流规则</h3><button className="button ghost" onClick={() => void query.refetch()}>刷新</button></div>{query.isLoading ? <div className="empty">加载中…</div> : <div className="table-wrap"><table><thead><tr><th>规则名</th><th>作用域</th><th>指标</th><th>限额</th><th>状态</th><th /></tr></thead><tbody>{query.data?.list.map(rule => <tr key={rule.id}><td>{rule.rule_name}</td><td>{rule.target_type}</td><td>{rule.metric}</td><td>{rule.limit_value} / {rule.window_seconds}s</td><td>{rule.enabled ? '启用' : '停用'}</td><td><button className="button ghost" onClick={() => void updateRateLimit(rule.id, { enabled: !rule.enabled }).then(() => query.refetch())}>切换</button><button className="button delete" onClick={() => void deleteRateLimit(rule.id).then(() => query.refetch())}>删除</button></td></tr>)}</tbody></table></div>}</section> }

export function QuotasPage() { const policies = useQuery({ queryKey: ['quota-policies'], queryFn: listQuotaPolicies }); const usage = useQuery({ queryKey: ['quota-usage'], queryFn: listQuotaUsage }); return <section className="panel"><div className="panel-head"><h3>周期配额</h3><button className="button ghost" onClick={() => { void policies.refetch(); void usage.refetch() }}>刷新</button></div>{policies.isLoading ? <div className="empty">加载中…</div> : <div className="table-wrap"><table><thead><tr><th>策略</th><th>作用域</th><th>周期</th><th>状态</th><th /></tr></thead><tbody>{policies.data?.list.map(policy => <tr key={policy.id}><td>{policy.policy_name}</td><td>{policy.scope_type} #{policy.scope_id}</td><td>{policy.period_type}</td><td>{policy.enabled ? '启用' : '停用'}</td><td><button className="button delete" onClick={() => void deleteQuotaPolicy(policy.id).then(() => policies.refetch())}>删除</button></td></tr>)}</tbody></table></div>}</section> }

export function PricingPage() { const query = useQuery({ queryKey: ['pricing'], queryFn: listPricing }); return <section className="panel"><div className="panel-head"><h3>计费定价</h3><button className="button ghost" onClick={() => void query.refetch()}>刷新</button></div>{query.isLoading ? <div className="empty">加载中…</div> : <div className="table-wrap"><table><thead><tr><th>渠道</th><th>模型</th><th>输入</th><th>输出</th><th /></tr></thead><tbody>{query.data?.list.map(row => <tr key={row.id}><td>{row.channel_name}</td><td>{row.model_name}</td><td>{row.input_price_per_1m}</td><td>{row.output_price_per_1m}</td><td><button className="button delete" onClick={() => void deletePricing({ channel_id: row.channel_id, model_name: row.model_name }).then(() => query.refetch())}>删除</button></td></tr>)}</tbody></table></div>}</section> }

export const SettingsPage = () => <div className="bento-grid"><section className="panel"><h3>系统设置</h3><p className="muted">管理端接口：/admin</p><a href="/healthz" target="_blank" rel="noreferrer">健康检查</a></section></div>
export const DocsPage = () => <section className="panel"><h3>API 文档</h3><p className="muted">下游兼容接口与管理端接口速查</p></section>
