import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { adminGet } from '../api/client'
import { Modal } from '../components/feedback/Modal'
import type { ListResponse, UsageLog } from '../types/api'

type Filter = { user_id: string; channel_id: string; model: string; status: string; start_time: string; end_time: string; page: number }
type Detail = UsageLog
const initial: Filter = { user_id: '', channel_id: '', model: '', status: '', start_time: '', end_time: '', page: 1 }
const localDateTime = (date: Date) => { const pad = (value: number) => String(value).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}` }

export function LogsPage() {
  const [draft, setDraft] = useState(initial); const [filter, setFilter] = useState(initial); const [detail, setDetail] = useState<Detail | null>(null); const [rangeError, setRangeError] = useState('')
  const query = useQuery({ queryKey: ['logs', filter], queryFn: () => adminGet<ListResponse<UsageLog>>('/usage-logs', { user_id: filter.user_id || undefined, channel_id: filter.channel_id || undefined, model: filter.model || undefined, status: filter.status || undefined, page: filter.page, page_size: 20, start_time: filter.start_time ? new Date(filter.start_time).toISOString() : undefined, end_time: filter.end_time ? new Date(filter.end_time).toISOString() : undefined }) })
  const update = (key: keyof Filter, value: string | number) => setDraft(current => ({ ...current, [key]: value }))
  const apply = (next: Filter) => { if (next.start_time && next.end_time && new Date(next.start_time) >= new Date(next.end_time)) { setRangeError('开始时间必须早于结束时间'); return } setRangeError(''); setFilter(next) }
  const setRange = (kind: 'today' | '24h' | '7d') => { const end = new Date(); const start = new Date(end); if (kind === 'today') start.setHours(0, 0, 0, 0); else start.setTime(end.getTime() - (kind === '24h' ? 86400000 : 7 * 86400000)); const next = { ...draft, start_time: localDateTime(start), end_time: localDateTime(end), page: 1 }; setDraft(next); apply(next) }
  const openDetail = async (id: number) => { try { setDetail(await adminGet<Detail>(`/usage-logs/${id}`)) } catch { setRangeError('请求详情加载失败') } }
  const totalPages = Math.max(1, Math.ceil((query.data?.total || 0) / 20))
  return <>
    <section className="panel"><div className="panel-head"><div><h3>请求日志</h3><p className="muted">usage_logs · 支持按用户/渠道/模型/状态/时间筛选</p></div><button className="button ghost" onClick={() => void query.refetch()}>刷新</button></div>
      <div className="filter-grid"><input placeholder="用户 ID" value={draft.user_id} onChange={event => update('user_id', event.target.value)} /><input placeholder="渠道 ID" value={draft.channel_id} onChange={event => update('channel_id', event.target.value)} /><input placeholder="模型" value={draft.model} onChange={event => update('model', event.target.value)} /><select value={draft.status} onChange={event => update('status', event.target.value)}><option value="">全部状态</option><option value="success">success</option><option value="error">error</option></select><label><span>开始时间</span><input type="datetime-local" value={draft.start_time} onChange={event => update('start_time', event.target.value)} /></label><label><span>结束时间</span><input type="datetime-local" value={draft.end_time} onChange={event => update('end_time', event.target.value)} /></label></div>
      <div className="filter-actions"><span className="muted filter-caption">快捷范围</span><button className="button ghost" onClick={() => setRange('today')}>今天</button><button className="button ghost" onClick={() => setRange('24h')}>最近 24 小时</button><button className="button ghost" onClick={() => setRange('7d')}>最近 7 天</button><button className="button primary" onClick={() => apply({ ...draft, page: 1 })}>查询</button><button className="button ghost" onClick={() => { setDraft(initial); apply(initial) }}>重置</button>{rangeError && <span className="error">{rangeError}</span>}</div>
      {query.isLoading ? <div className="empty">加载中…</div> : query.isError ? <div className="empty error">加载失败，请重试。</div> : query.data?.list.length ? <div className="table-wrap"><table><thead><tr><th>时间</th><th>Request ID</th><th>用户 / 模型</th><th>渠道</th><th>Tokens</th><th>TTFT</th><th>耗时</th><th>费用</th><th>状态</th><th>详情</th></tr></thead><tbody>{query.data.list.map(row => <tr key={row.id}><td className="mono">{new Date(row.created_at).toLocaleString('zh-CN', { hour12: false })}</td><td className="mono log-id">{row.request_id}</td><td><b>#{row.user_id ?? '—'}</b><br /><span className="muted">{row.model}</span></td><td>{row.channel_name || (row.channel_id == null ? '渠道已删除' : `#${row.channel_id}`)}</td><td className="mono">{row.total_tokens.toLocaleString()}</td><td className="mono">{row.ttft_ms == null ? '—' : `${row.ttft_ms}ms`}</td><td className="mono">{(row.duration_ms / 1000).toFixed(1)}s</td><td className="mono">${row.total_cost}</td><td><span className={`badge ${row.status === 'success' ? 'ok-bg' : 'danger-bg'}`}>{row.status === 'success' ? '成功' : row.error_code || '失败'}</span></td><td><button className="button ghost" onClick={() => void openDetail(row.id)}>查看</button></td></tr>)}</tbody></table></div> : <div className="empty">当前筛选条件下暂无日志</div>}
      <div className="pagination"><span>共 {query.data?.total || 0} 条 · 第 {filter.page} / {totalPages} 页</span><span><button className="button ghost" disabled={filter.page <= 1} onClick={() => setFilter({ ...filter, page: filter.page - 1 })}>上一页</button><button className="button ghost" disabled={filter.page >= totalPages} onClick={() => setFilter({ ...filter, page: filter.page + 1 })}>下一页</button></span></div>
    </section>
     {detail && <Modal title="请求详情" onClose={() => setDetail(null)}><div className="detail-list">{[['Request ID', detail.request_id], ['用户 / Key', `#${detail.user_id ?? '—'} / #${detail.api_key_id ?? '—'}`], ['渠道', detail.channel_name || (detail.channel_id == null ? '渠道已删除' : `#${detail.channel_id}`)], ['模型 / 上游模型', `${detail.model} / ${String(detail.upstream_model || '—')}`], ['输入 / 输出 / 缓存 tokens', `${detail.input_tokens ?? '—'} / ${detail.output_tokens ?? '—'} / ${detail.cached_input_tokens ?? '—'}`], ['单价 输入 / 输出', `$${detail.unit_price_input_per_1m ?? '—'} / $${detail.unit_price_output_per_1m ?? '—'}`], ['费用', `$${detail.total_cost}`], ['耗时 / TTFT', `${detail.duration_ms}ms / ${detail.ttft_ms == null ? '—' : `${detail.ttft_ms}ms`}`], ['状态 / 错误码', `${detail.status} / ${detail.error_code || '—'}`], ['客户端 IP', detail.client_ip || '—'], ['时间', detail.created_at]].map(([label, value]) => <div key={String(label)}><span>{String(label)}</span><b>{String(value)}</b></div>)}</div></Modal>}
  </>
}
