import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { createUser, deleteUser, getUserBalance, listBalanceTransactions, listKeys, listUserKeys, listUsers, rechargeUser, createUserKey, updateUser, updateUserStatus } from '../api/accounts'
import { Modal } from '../components/feedback/Modal'
import type { ClientKey, KeyCreateInput, RechargeInput, User, UserCreateInput, UserUpdateInput } from '../types/api'

const value = (input: unknown, fallback = '—') => input == null || input === '' ? fallback : String(input)

export function UsersPage() {
  const client = useQueryClient()
  const users = useQuery({ queryKey: ['users'], queryFn: () => listUsers() })
  const keys = useQuery({ queryKey: ['keys'], queryFn: () => listKeys() })
  const [editor, setEditor] = useState<User | null | undefined>()
  const [recharge, setRecharge] = useState<User | null>(null)
  const [account, setAccount] = useState<User | null>(null)
  const [message, setMessage] = useState('')
  const refresh = () => Promise.all([users.refetch(), keys.refetch()])
  const submitUser = async (event: React.FormEvent<HTMLFormElement>) => { const form = new FormData(event.currentTarget); const common = { nickname: String(form.get('nickname') || ''), user_group: String(form.get('user_group') || ''), ...(form.get('password') ? { password: String(form.get('password')) } : {}) }; if (editor?.id) { const body: UserUpdateInput = common; await updateUser(editor.id, body) } else { const body: UserCreateInput = { ...common, status: 'active' }; await createUser(body) } await refresh(); setEditor(undefined) }
  return <><section className="panel"><div className="panel-head"><div><h3>下游用户</h3><p className="muted">users · 余额 / 分组 / 状态</p></div><button className="button primary" onClick={() => setEditor(null)}>新建用户</button></div>{message && <p className="error">{message}</p>}{users.isLoading ? <div className="empty">加载中…</div> : <div className="table-wrap"><table><thead><tr><th>ID</th><th>昵称</th><th>分组</th><th>状态</th><th>余额</th><th>操作</th></tr></thead><tbody>{users.data?.list.map(user => <tr key={user.id}><td>#{user.id}</td><td>{user.nickname}</td><td>{user.user_group}</td><td>{user.status}</td><td>${user.balance.available_balance}</td><td><button className="button ghost" onClick={() => setEditor(user)}>编辑</button><button className="button ghost" onClick={() => setRecharge(user)}>充值</button><button className="button ghost" onClick={() => setAccount(user)}>账户</button><button className="button ghost" onClick={() => void updateUserStatus(user.id, { status: user.status === 'active' ? 'suspended' : 'active' }).then(refresh)}>切换状态</button><button className="button delete" onClick={() => { if (window.confirm('删除该用户？')) void deleteUser(user.id).then(refresh) }}>删除</button></td></tr>)}</tbody></table></div>}</section><section className="panel"><div className="panel-head"><h3>网关 Key</h3></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>用户</th><th>名称</th><th>前缀</th><th>状态</th></tr></thead><tbody>{keys.data?.list.map(key => <tr key={key.id}><td>#{key.id}</td><td>#{key.user_id}</td><td>{key.key_name}</td><td>{key.prefix}</td><td>{key.is_active ? '启用' : '停用'}</td></tr>)}</tbody></table></div></section>{editor !== undefined && <UserEditor user={editor} onClose={() => setEditor(undefined)} onSubmit={submitUser} />}{recharge && <Recharge user={recharge} onClose={() => setRecharge(null)} onSaved={() => { setRecharge(null); void refresh() }} />}{account && <Account user={account} onClose={() => setAccount(null)} onCreated={key => setMessage(`新 Key：${key}`)} />}</>
}

function UserEditor({ user, onClose, onSubmit }: { user: User | null; onClose: () => void; onSubmit: (event: React.FormEvent<HTMLFormElement>) => Promise<void> }) { return <Modal title={user ? '编辑用户' : '新建用户'} submitText="保存" onClose={onClose} onSubmit={onSubmit}><Field label="昵称" name="nickname" defaultValue={user?.nickname} required /><Field label="分组" name="user_group" defaultValue={user?.user_group || 'default'} /><Field label="密码" name="password" /></Modal> }
function Recharge({ user, onClose, onSaved }: { user: User; onClose: () => void; onSaved: () => void }) { return <Modal title={`充值 · ${user.nickname}`} submitText="充值" onClose={onClose} onSubmit={async event => { const form = new FormData(event.currentTarget); const input: RechargeInput = { amount: String(form.get('amount') || ''), description: String(form.get('description') || '') }; await rechargeUser(user.id, input); onSaved() }}><Field label="金额" name="amount" required /><Field label="备注" name="description" /></Modal> }
function Account({ user, onClose, onCreated }: { user: User; onClose: () => void; onCreated: (key: string) => void }) { const balance = useQuery({ queryKey: ['balance', user.id], queryFn: () => getUserBalance(user.id) }); const transactions = useQuery({ queryKey: ['transactions', user.id], queryFn: () => listBalanceTransactions(user.id) }); const keys = useQuery({ queryKey: ['user-keys', user.id], queryFn: () => listUserKeys(user.id) }); return <Modal title={`账户 · ${user.nickname}`} onClose={onClose}><p>可用余额：${balance.data?.available_balance || '0.000000'}</p><p>冻结余额：${balance.data?.frozen_balance || '0.000000'}</p><button className="button primary" onClick={async () => { const input: KeyCreateInput = { key_name: 'default', prefix: 'sk-', permissions: { models: ['*'] }, is_active: true }; const result = await createUserKey(user.id, input); onCreated(result.full_key) }}>创建 Key</button><p>流水：{transactions.data?.total || 0} 条，Key：{keys.data?.total || 0} 个</p></Modal> }
function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label><span>{label}</span><input {...props} /></label> }
