// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChannelSecret = `-- name: GetChannelSecret :one
SELECT id, name, base_url, api_key_ciphertext, auth_type, status, weight, priority, balance
FROM channels
WHERE id = $1
`

type GetChannelSecretRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	BaseUrl          string         `json:"base_url"`
	ApiKeyCiphertext string         `json:"api_key_ciphertext"`
	AuthType         string         `json:"auth_type"`
	Status           int32          `json:"status"`
	Weight           int32          `json:"weight"`
	Priority         int32          `json:"priority"`
	Balance          pgtype.Numeric `json:"balance"`
}

func (q *Queries) GetChannelSecret(ctx context.Context, id int64) (GetChannelSecretRow, error) {
	row := q.db.QueryRow(ctx, getChannelSecret, id)
	var i GetChannelSecretRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyCiphertext,
		&i.AuthType,
		&i.Status,
		&i.Weight,
		&i.Priority,
		&i.Balance,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT
    c.id,
    c.name,
    c.base_url,
    c.auth_type,
    c.status,
    c.weight,
    c.priority,
    c.balance,
    count(cm.id)::int AS model_count
FROM channels c
LEFT JOIN channel_models cm ON cm.channel_id = c.id
GROUP BY c.id
ORDER BY c.id
`

type ListChannelsRow struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	BaseUrl    string         `json:"base_url"`
	AuthType   string         `json:"auth_type"`
	Status     int32          `json:"status"`
	Weight     int32          `json:"weight"`
	Priority   int32          `json:"priority"`
	Balance    pgtype.Numeric `json:"balance"`
	ModelCount int32          `json:"model_count"`
}

func (q *Queries) ListChannels(ctx context.Context) ([]ListChannelsRow, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelsRow{}
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.AuthType,
			&i.Status,
			&i.Weight,
			&i.Priority,
			&i.Balance,
			&i.ModelCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
