// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package sqlc

import (
	"context"
)

const listCatalogModels = `-- name: ListCatalogModels :many
SELECT
    cm.model_name,
    c.id AS channel_id,
    c.name AS channel_name,
    cm.upstream_model,
    cm.enabled
FROM channel_models cm
JOIN channels c ON c.id = cm.channel_id
WHERE $1::boolean = false OR cm.enabled = true
ORDER BY cm.model_name, c.priority DESC, c.weight DESC, c.id
`

type ListCatalogModelsRow struct {
	ModelName     string `json:"model_name"`
	ChannelID     int64  `json:"channel_id"`
	ChannelName   string `json:"channel_name"`
	UpstreamModel string `json:"upstream_model"`
	Enabled       bool   `json:"enabled"`
}

func (q *Queries) ListCatalogModels(ctx context.Context, enabledOnly bool) ([]ListCatalogModelsRow, error) {
	rows, err := q.db.Query(ctx, listCatalogModels, enabledOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogModelsRow{}
	for rows.Next() {
		var i ListCatalogModelsRow
		if err := rows.Scan(
			&i.ModelName,
			&i.ChannelID,
			&i.ChannelName,
			&i.UpstreamModel,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelModels = `-- name: ListChannelModels :many
SELECT id, model_name, upstream_model, enabled
FROM channel_models
WHERE channel_id = $1
ORDER BY id
`

type ListChannelModelsRow struct {
	ID            int64  `json:"id"`
	ModelName     string `json:"model_name"`
	UpstreamModel string `json:"upstream_model"`
	Enabled       bool   `json:"enabled"`
}

func (q *Queries) ListChannelModels(ctx context.Context, channelID int64) ([]ListChannelModelsRow, error) {
	rows, err := q.db.Query(ctx, listChannelModels, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelModelsRow{}
	for rows.Next() {
		var i ListChannelModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.ModelName,
			&i.UpstreamModel,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
