// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPricing = `-- name: ListPricing :many
SELECT
    p.id,
    p.channel_id,
    c.name AS channel_name,
    p.model_name,
    cm.upstream_model,
    p.input_price_per_1m,
    p.output_price_per_1m,
    p.cached_input_price_per_1m,
    p.currency
FROM model_pricing p
JOIN channels c ON c.id = p.channel_id
LEFT JOIN channel_models cm ON cm.channel_id = p.channel_id AND cm.model_name = p.model_name
ORDER BY p.id
`

type ListPricingRow struct {
	ID                    int64          `json:"id"`
	ChannelID             int64          `json:"channel_id"`
	ChannelName           string         `json:"channel_name"`
	ModelName             string         `json:"model_name"`
	UpstreamModel         pgtype.Text    `json:"upstream_model"`
	InputPricePer1m       pgtype.Numeric `json:"input_price_per_1m"`
	OutputPricePer1m      pgtype.Numeric `json:"output_price_per_1m"`
	CachedInputPricePer1m pgtype.Numeric `json:"cached_input_price_per_1m"`
	Currency              string         `json:"currency"`
}

func (q *Queries) ListPricing(ctx context.Context) ([]ListPricingRow, error) {
	rows, err := q.db.Query(ctx, listPricing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPricingRow{}
	for rows.Next() {
		var i ListPricingRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ChannelName,
			&i.ModelName,
			&i.UpstreamModel,
			&i.InputPricePer1m,
			&i.OutputPricePer1m,
			&i.CachedInputPricePer1m,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
