// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountRateLimitRules(ctx context.Context, enabled pgtype.Bool) (int32, error)
	CountUsers(ctx context.Context) (int32, error)
	GetChannelSecret(ctx context.Context, id int64) (GetChannelSecretRow, error)
	GetUsageLog(ctx context.Context, id int64) (GetUsageLogRow, error)
	GetUserBalance(ctx context.Context, userID int64) (GetUserBalanceRow, error)
	ListBalanceTransactions(ctx context.Context, arg ListBalanceTransactionsParams) ([]BalanceTransaction, error)
	ListCatalogModels(ctx context.Context, enabledOnly bool) ([]ListCatalogModelsRow, error)
	ListChannelModels(ctx context.Context, channelID int64) ([]ListChannelModelsRow, error)
	ListChannels(ctx context.Context) ([]ListChannelsRow, error)
	ListKeys(ctx context.Context, arg ListKeysParams) ([]ListKeysRow, error)
	ListPricing(ctx context.Context) ([]ListPricingRow, error)
	ListRateLimitRules(ctx context.Context, arg ListRateLimitRulesParams) ([]ListRateLimitRulesRow, error)
	ListUsageLogs(ctx context.Context, arg ListUsageLogsParams) ([]ListUsageLogsRow, error)
	ListUserKeys(ctx context.Context, arg ListUserKeysParams) ([]ListUserKeysRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	StatsChannels(ctx context.Context, arg StatsChannelsParams) ([]StatsChannelsRow, error)
	StatsOverview(ctx context.Context, arg StatsOverviewParams) (StatsOverviewRow, error)
}

var _ Querier = (*Queries)(nil)
