// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limits.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRateLimitRules = `-- name: CountRateLimitRules :one
SELECT count(*)::int
FROM rate_limit_rules
WHERE $1::boolean IS NULL OR enabled = $1::boolean
`

func (q *Queries) CountRateLimitRules(ctx context.Context, enabled pgtype.Bool) (int32, error) {
	row := q.db.QueryRow(ctx, countRateLimitRules, enabled)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listRateLimitRules = `-- name: ListRateLimitRules :many
SELECT id, rule_name, target_type, target_value, metric, limit_value, window_seconds, action, priority, enabled, extras
FROM rate_limit_rules
WHERE $3::boolean IS NULL OR enabled = $3::boolean
ORDER BY priority, id
LIMIT $1 OFFSET $2
`

type ListRateLimitRulesParams struct {
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Enabled pgtype.Bool `json:"enabled"`
}

type ListRateLimitRulesRow struct {
	ID            int64  `json:"id"`
	RuleName      string `json:"rule_name"`
	TargetType    string `json:"target_type"`
	TargetValue   string `json:"target_value"`
	Metric        string `json:"metric"`
	LimitValue    int64  `json:"limit_value"`
	WindowSeconds int32  `json:"window_seconds"`
	Action        string `json:"action"`
	Priority      int32  `json:"priority"`
	Enabled       bool   `json:"enabled"`
	Extras        []byte `json:"extras"`
}

func (q *Queries) ListRateLimitRules(ctx context.Context, arg ListRateLimitRulesParams) ([]ListRateLimitRulesRow, error) {
	rows, err := q.db.Query(ctx, listRateLimitRules, arg.Limit, arg.Offset, arg.Enabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRateLimitRulesRow{}
	for rows.Next() {
		var i ListRateLimitRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleName,
			&i.TargetType,
			&i.TargetValue,
			&i.Metric,
			&i.LimitValue,
			&i.WindowSeconds,
			&i.Action,
			&i.Priority,
			&i.Enabled,
			&i.Extras,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
