// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUsageLog = `-- name: GetUsageLog :one
SELECT
    l.id,
    l.request_id,
    l.user_id,
    l.api_key_id,
    l.channel_id,
    c.name AS channel_name,
    l.model,
    l.upstream_model,
    l.input_tokens,
    l.output_tokens,
    l.cached_input_tokens,
    l.total_tokens,
    l.unit_price_input_per_1m,
    l.unit_price_output_per_1m,
    l.total_cost,
    l.duration_ms,
    l.ttft_ms,
    l.status,
    l.error_code,
    l.client_ip,
    l.created_at
FROM usage_logs l
LEFT JOIN channels c ON c.id = l.channel_id
WHERE l.id = $1
`

type GetUsageLogRow struct {
	ID                   int64              `json:"id"`
	RequestID            string             `json:"request_id"`
	UserID               pgtype.Int8        `json:"user_id"`
	ApiKeyID             pgtype.Int8        `json:"api_key_id"`
	ChannelID            pgtype.Int8        `json:"channel_id"`
	ChannelName          pgtype.Text        `json:"channel_name"`
	Model                string             `json:"model"`
	UpstreamModel        string             `json:"upstream_model"`
	InputTokens          int64              `json:"input_tokens"`
	OutputTokens         int64              `json:"output_tokens"`
	CachedInputTokens    int64              `json:"cached_input_tokens"`
	TotalTokens          int64              `json:"total_tokens"`
	UnitPriceInputPer1m  pgtype.Numeric     `json:"unit_price_input_per_1m"`
	UnitPriceOutputPer1m pgtype.Numeric     `json:"unit_price_output_per_1m"`
	TotalCost            pgtype.Numeric     `json:"total_cost"`
	DurationMs           int64              `json:"duration_ms"`
	TtftMs               pgtype.Int8        `json:"ttft_ms"`
	Status               string             `json:"status"`
	ErrorCode            string             `json:"error_code"`
	ClientIp             string             `json:"client_ip"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUsageLog(ctx context.Context, id int64) (GetUsageLogRow, error) {
	row := q.db.QueryRow(ctx, getUsageLog, id)
	var i GetUsageLogRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.ChannelID,
		&i.ChannelName,
		&i.Model,
		&i.UpstreamModel,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedInputTokens,
		&i.TotalTokens,
		&i.UnitPriceInputPer1m,
		&i.UnitPriceOutputPer1m,
		&i.TotalCost,
		&i.DurationMs,
		&i.TtftMs,
		&i.Status,
		&i.ErrorCode,
		&i.ClientIp,
		&i.CreatedAt,
	)
	return i, err
}

const listUsageLogs = `-- name: ListUsageLogs :many
SELECT
    l.id,
    l.request_id,
    l.user_id,
    l.api_key_id,
    l.channel_id,
    c.name AS channel_name,
    l.model,
    l.upstream_model,
    l.input_tokens,
    l.output_tokens,
    l.cached_input_tokens,
    l.total_tokens,
    l.unit_price_input_per_1m,
    l.unit_price_output_per_1m,
    l.total_cost,
    l.duration_ms,
    l.ttft_ms,
    l.status,
    l.error_code,
    l.client_ip,
    l.created_at
FROM usage_logs l
LEFT JOIN channels c ON c.id = l.channel_id
ORDER BY l.created_at DESC, l.id DESC
LIMIT $1 OFFSET $2
`

type ListUsageLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsageLogsRow struct {
	ID                   int64              `json:"id"`
	RequestID            string             `json:"request_id"`
	UserID               pgtype.Int8        `json:"user_id"`
	ApiKeyID             pgtype.Int8        `json:"api_key_id"`
	ChannelID            pgtype.Int8        `json:"channel_id"`
	ChannelName          pgtype.Text        `json:"channel_name"`
	Model                string             `json:"model"`
	UpstreamModel        string             `json:"upstream_model"`
	InputTokens          int64              `json:"input_tokens"`
	OutputTokens         int64              `json:"output_tokens"`
	CachedInputTokens    int64              `json:"cached_input_tokens"`
	TotalTokens          int64              `json:"total_tokens"`
	UnitPriceInputPer1m  pgtype.Numeric     `json:"unit_price_input_per_1m"`
	UnitPriceOutputPer1m pgtype.Numeric     `json:"unit_price_output_per_1m"`
	TotalCost            pgtype.Numeric     `json:"total_cost"`
	DurationMs           int64              `json:"duration_ms"`
	TtftMs               pgtype.Int8        `json:"ttft_ms"`
	Status               string             `json:"status"`
	ErrorCode            string             `json:"error_code"`
	ClientIp             string             `json:"client_ip"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsageLogs(ctx context.Context, arg ListUsageLogsParams) ([]ListUsageLogsRow, error) {
	rows, err := q.db.Query(ctx, listUsageLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsageLogsRow{}
	for rows.Next() {
		var i ListUsageLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.UserID,
			&i.ApiKeyID,
			&i.ChannelID,
			&i.ChannelName,
			&i.Model,
			&i.UpstreamModel,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedInputTokens,
			&i.TotalTokens,
			&i.UnitPriceInputPer1m,
			&i.UnitPriceOutputPer1m,
			&i.TotalCost,
			&i.DurationMs,
			&i.TtftMs,
			&i.Status,
			&i.ErrorCode,
			&i.ClientIp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsChannels = `-- name: StatsChannels :many
SELECT
    l.channel_id,
    coalesce(c.name, '') AS channel_name,
    count(*)::bigint AS request_count,
    count(*) FILTER (WHERE l.status = 'success')::bigint AS success_count,
    count(*) FILTER (WHERE l.status <> 'success')::bigint AS error_count,
    coalesce(sum(l.total_tokens), 0)::bigint AS total_tokens,
    coalesce(sum(l.total_cost), 0)::numeric(20, 6) AS total_cost
FROM usage_logs l
LEFT JOIN channels c ON c.id = l.channel_id
WHERE l.created_at >= $1 AND l.created_at <= $2
GROUP BY l.channel_id, c.name
ORDER BY request_count DESC, l.channel_id
`

type StatsChannelsParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type StatsChannelsRow struct {
	ChannelID    pgtype.Int8    `json:"channel_id"`
	ChannelName  string         `json:"channel_name"`
	RequestCount int64          `json:"request_count"`
	SuccessCount int64          `json:"success_count"`
	ErrorCount   int64          `json:"error_count"`
	TotalTokens  int64          `json:"total_tokens"`
	TotalCost    pgtype.Numeric `json:"total_cost"`
}

func (q *Queries) StatsChannels(ctx context.Context, arg StatsChannelsParams) ([]StatsChannelsRow, error) {
	rows, err := q.db.Query(ctx, statsChannels, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsChannelsRow{}
	for rows.Next() {
		var i StatsChannelsRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelName,
			&i.RequestCount,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.TotalTokens,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsOverview = `-- name: StatsOverview :one
SELECT
    count(*)::bigint AS request_count,
    count(*) FILTER (WHERE status = 'success')::bigint AS success_count,
    count(*) FILTER (WHERE status <> 'success')::bigint AS error_count,
    coalesce(sum(total_tokens), 0)::bigint AS total_tokens,
    coalesce(sum(total_cost), 0)::numeric(20, 6) AS total_cost,
    count(DISTINCT user_id)::bigint AS active_user_count
FROM usage_logs
WHERE created_at >= $1 AND created_at <= $2
`

type StatsOverviewParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type StatsOverviewRow struct {
	RequestCount    int64          `json:"request_count"`
	SuccessCount    int64          `json:"success_count"`
	ErrorCount      int64          `json:"error_count"`
	TotalTokens     int64          `json:"total_tokens"`
	TotalCost       pgtype.Numeric `json:"total_cost"`
	ActiveUserCount int64          `json:"active_user_count"`
}

func (q *Queries) StatsOverview(ctx context.Context, arg StatsOverviewParams) (StatsOverviewRow, error) {
	row := q.db.QueryRow(ctx, statsOverview, arg.CreatedAt, arg.CreatedAt_2)
	var i StatsOverviewRow
	err := row.Scan(
		&i.RequestCount,
		&i.SuccessCount,
		&i.ErrorCount,
		&i.TotalTokens,
		&i.TotalCost,
		&i.ActiveUserCount,
	)
	return i, err
}
