// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*)::int FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserBalance = `-- name: GetUserBalance :one
SELECT user_id, available_balance, frozen_balance
FROM user_balances
WHERE user_id = $1
`

type GetUserBalanceRow struct {
	UserID           int64          `json:"user_id"`
	AvailableBalance pgtype.Numeric `json:"available_balance"`
	FrozenBalance    pgtype.Numeric `json:"frozen_balance"`
}

func (q *Queries) GetUserBalance(ctx context.Context, userID int64) (GetUserBalanceRow, error) {
	row := q.db.QueryRow(ctx, getUserBalance, userID)
	var i GetUserBalanceRow
	err := row.Scan(&i.UserID, &i.AvailableBalance, &i.FrozenBalance)
	return i, err
}

const listBalanceTransactions = `-- name: ListBalanceTransactions :many
SELECT id, user_id, tx_type, amount, balance_after, related_order_id, description, created_at
FROM balance_transactions
WHERE user_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListBalanceTransactionsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBalanceTransactions(ctx context.Context, arg ListBalanceTransactionsParams) ([]BalanceTransaction, error) {
	rows, err := q.db.Query(ctx, listBalanceTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceTransaction{}
	for rows.Next() {
		var i BalanceTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TxType,
			&i.Amount,
			&i.BalanceAfter,
			&i.RelatedOrderID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeys = `-- name: ListKeys :many
SELECT id, user_id, key_name, prefix, is_active, last_used_at, expires_at
FROM client_api_keys
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListKeysParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListKeysRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	KeyName    string             `json:"key_name"`
	Prefix     string             `json:"prefix"`
	IsActive   bool               `json:"is_active"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListKeys(ctx context.Context, arg ListKeysParams) ([]ListKeysRow, error) {
	rows, err := q.db.Query(ctx, listKeys, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeysRow{}
	for rows.Next() {
		var i ListKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyName,
			&i.Prefix,
			&i.IsActive,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserKeys = `-- name: ListUserKeys :many
SELECT id, user_id, key_name, prefix, is_active, last_used_at, expires_at
FROM client_api_keys
WHERE user_id = $1
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListUserKeysParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUserKeysRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	KeyName    string             `json:"key_name"`
	Prefix     string             `json:"prefix"`
	IsActive   bool               `json:"is_active"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListUserKeys(ctx context.Context, arg ListUserKeysParams) ([]ListUserKeysRow, error) {
	rows, err := q.db.Query(ctx, listUserKeys, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserKeysRow{}
	for rows.Next() {
		var i ListUserKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyName,
			&i.Prefix,
			&i.IsActive,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
    u.id,
    u.nickname,
    u.user_group,
    u.status,
    b.available_balance,
    b.frozen_balance
FROM users u
LEFT JOIN user_balances b ON b.user_id = u.id
ORDER BY u.id
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID               int64          `json:"id"`
	Nickname         string         `json:"nickname"`
	UserGroup        string         `json:"user_group"`
	Status           string         `json:"status"`
	AvailableBalance pgtype.Numeric `json:"available_balance"`
	FrozenBalance    pgtype.Numeric `json:"frozen_balance"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.UserGroup,
			&i.Status,
			&i.AvailableBalance,
			&i.FrozenBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
