package postgres

import (
	"LLMGateway/internal/db/sqlc"
	"LLMGateway/internal/store"

	"github.com/jackc/pgx/v5/pgxpool"
)

// Store is the PostgreSQL-backed implementation of store.Store.
//
// The SQL queries are generated by sqlc from db/queries into internal/db/sqlc.
// Concrete query wiring is implemented by the PostgreSQL store sub-issue; until
// then every method reports store.ErrNotImplemented so the assembly path stays
// real without silently returning empty data.
type Store struct {
	pool    *pgxpool.Pool
	queries *sqlc.Queries
}

var (
	_ store.Store        = (*Store)(nil)
	_ store.ChannelStore = (*Store)(nil)
)

func New(pool *pgxpool.Pool) *Store {
	return &Store{pool: pool, queries: sqlc.New(pool)}
}
