// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_health.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteChannelHealth = `-- name: DeleteChannelHealth :execrows
DELETE FROM channel_health WHERE channel_id = $1
`

func (q *Queries) DeleteChannelHealth(ctx context.Context, channelID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelHealth, channelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannelHealth = `-- name: GetChannelHealth :one
SELECT channel_id, state, consecutive_failures, success_count, failure_count, opened_at, updated_at
FROM channel_health
WHERE channel_id = $1
`

func (q *Queries) GetChannelHealth(ctx context.Context, channelID int64) (ChannelHealth, error) {
	row := q.db.QueryRow(ctx, getChannelHealth, channelID)
	var i ChannelHealth
	err := row.Scan(
		&i.ChannelID,
		&i.State,
		&i.ConsecutiveFailures,
		&i.SuccessCount,
		&i.FailureCount,
		&i.OpenedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelHealth = `-- name: ListChannelHealth :many
SELECT channel_id, state, consecutive_failures, success_count, failure_count, opened_at, updated_at
FROM channel_health
ORDER BY channel_id
`

func (q *Queries) ListChannelHealth(ctx context.Context) ([]ChannelHealth, error) {
	rows, err := q.db.Query(ctx, listChannelHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelHealth{}
	for rows.Next() {
		var i ChannelHealth
		if err := rows.Scan(
			&i.ChannelID,
			&i.State,
			&i.ConsecutiveFailures,
			&i.SuccessCount,
			&i.FailureCount,
			&i.OpenedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChannelHealth = `-- name: UpsertChannelHealth :exec
INSERT INTO channel_health (channel_id, state, consecutive_failures, success_count, failure_count, opened_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    now()
)
ON CONFLICT (channel_id) DO UPDATE SET
    state = EXCLUDED.state,
    consecutive_failures = EXCLUDED.consecutive_failures,
    success_count = EXCLUDED.success_count,
    failure_count = EXCLUDED.failure_count,
    opened_at = EXCLUDED.opened_at,
    updated_at = now()
`

type UpsertChannelHealthParams struct {
	ChannelID           int64              `json:"channel_id"`
	State               string             `json:"state"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	SuccessCount        int64              `json:"success_count"`
	FailureCount        int64              `json:"failure_count"`
	OpenedAt            pgtype.Timestamptz `json:"opened_at"`
}

func (q *Queries) UpsertChannelHealth(ctx context.Context, arg UpsertChannelHealthParams) error {
	_, err := q.db.Exec(ctx, upsertChannelHealth,
		arg.ChannelID,
		arg.State,
		arg.ConsecutiveFailures,
		arg.SuccessCount,
		arg.FailureCount,
		arg.OpenedAt,
	)
	return err
}
