// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BalanceTransaction struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	TxType         string             `json:"tx_type"`
	Amount         pgtype.Numeric     `json:"amount"`
	BalanceAfter   pgtype.Numeric     `json:"balance_after"`
	RelatedOrderID pgtype.Text        `json:"related_order_id"`
	Description    string             `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Channel struct {
	ID               int64              `json:"id"`
	Name             string             `json:"name"`
	BaseUrl          string             `json:"base_url"`
	ApiKeyCiphertext string             `json:"api_key_ciphertext"`
	AuthType         string             `json:"auth_type"`
	Status           int32              `json:"status"`
	Weight           int32              `json:"weight"`
	Priority         int32              `json:"priority"`
	Balance          pgtype.Numeric     `json:"balance"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ChannelHealth struct {
	ChannelID           int64              `json:"channel_id"`
	State               string             `json:"state"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	SuccessCount        int64              `json:"success_count"`
	FailureCount        int64              `json:"failure_count"`
	OpenedAt            pgtype.Timestamptz `json:"opened_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type ChannelModel struct {
	ID            int64              `json:"id"`
	ChannelID     int64              `json:"channel_id"`
	ModelName     string             `json:"model_name"`
	UpstreamModel string             `json:"upstream_model"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ClientApiKey struct {
	ID                 int64              `json:"id"`
	UserID             int64              `json:"user_id"`
	KeyName            string             `json:"key_name"`
	Prefix             string             `json:"prefix"`
	KeyHash            string             `json:"key_hash"`
	Permissions        []byte             `json:"permissions"`
	RateLimitOverrides []byte             `json:"rate_limit_overrides"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	IsActive           bool               `json:"is_active"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ModelPricing struct {
	ID                    int64              `json:"id"`
	ChannelID             int64              `json:"channel_id"`
	ModelName             string             `json:"model_name"`
	InputPricePer1m       pgtype.Numeric     `json:"input_price_per_1m"`
	OutputPricePer1m      pgtype.Numeric     `json:"output_price_per_1m"`
	CachedInputPricePer1m pgtype.Numeric     `json:"cached_input_price_per_1m"`
	Currency              string             `json:"currency"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type RateLimitRule struct {
	ID            int64              `json:"id"`
	RuleName      string             `json:"rule_name"`
	TargetType    string             `json:"target_type"`
	TargetValue   string             `json:"target_value"`
	Metric        string             `json:"metric"`
	LimitValue    int64              `json:"limit_value"`
	WindowSeconds int32              `json:"window_seconds"`
	Action        string             `json:"action"`
	Priority      int32              `json:"priority"`
	Enabled       bool               `json:"enabled"`
	Extras        []byte             `json:"extras"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UsageLog struct {
	ID                   int64              `json:"id"`
	RequestID            string             `json:"request_id"`
	UserID               pgtype.Int8        `json:"user_id"`
	ApiKeyID             pgtype.Int8        `json:"api_key_id"`
	ChannelID            pgtype.Int8        `json:"channel_id"`
	Model                string             `json:"model"`
	UpstreamModel        string             `json:"upstream_model"`
	InputTokens          int64              `json:"input_tokens"`
	OutputTokens         int64              `json:"output_tokens"`
	CachedInputTokens    int64              `json:"cached_input_tokens"`
	TotalTokens          int64              `json:"total_tokens"`
	UnitPriceInputPer1m  pgtype.Numeric     `json:"unit_price_input_per_1m"`
	UnitPriceOutputPer1m pgtype.Numeric     `json:"unit_price_output_per_1m"`
	TotalCost            pgtype.Numeric     `json:"total_cost"`
	DurationMs           int64              `json:"duration_ms"`
	TtftMs               pgtype.Int8        `json:"ttft_ms"`
	Status               string             `json:"status"`
	ErrorCode            string             `json:"error_code"`
	ClientIp             string             `json:"client_ip"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Nickname     string             `json:"nickname"`
	UserGroup    string             `json:"user_group"`
	Status       string             `json:"status"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserBalance struct {
	UserID           int64              `json:"user_id"`
	AvailableBalance pgtype.Numeric     `json:"available_balance"`
	FrozenBalance    pgtype.Numeric     `json:"frozen_balance"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
