// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quotas.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuotaPolicy = `-- name: CreateQuotaPolicy :one
INSERT INTO quota_policies (policy_name, scope_type, user_id, api_key_id, period_type, token_limit, cost_limit, enabled)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
RETURNING id
`

type CreateQuotaPolicyParams struct {
	PolicyName string         `json:"policy_name"`
	ScopeType  string         `json:"scope_type"`
	UserID     pgtype.Int8    `json:"user_id"`
	ApiKeyID   pgtype.Int8    `json:"api_key_id"`
	PeriodType string         `json:"period_type"`
	TokenLimit pgtype.Int8    `json:"token_limit"`
	CostLimit  pgtype.Numeric `json:"cost_limit"`
	Enabled    bool           `json:"enabled"`
}

func (q *Queries) CreateQuotaPolicy(ctx context.Context, arg CreateQuotaPolicyParams) (int64, error) {
	row := q.db.QueryRow(ctx, createQuotaPolicy,
		arg.PolicyName,
		arg.ScopeType,
		arg.UserID,
		arg.ApiKeyID,
		arg.PeriodType,
		arg.TokenLimit,
		arg.CostLimit,
		arg.Enabled,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteQuotaPolicy = `-- name: DeleteQuotaPolicy :execrows
UPDATE quota_policies
SET enabled = false, deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteQuotaPolicy(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQuotaPolicy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getQuotaPolicy = `-- name: GetQuotaPolicy :one
SELECT id, policy_name, scope_type, user_id, api_key_id, period_type,
       token_limit, cost_limit::text AS cost_limit, enabled
FROM quota_policies
WHERE id = $1 AND deleted_at IS NULL
`

type GetQuotaPolicyRow struct {
	ID         int64       `json:"id"`
	PolicyName string      `json:"policy_name"`
	ScopeType  string      `json:"scope_type"`
	UserID     pgtype.Int8 `json:"user_id"`
	ApiKeyID   pgtype.Int8 `json:"api_key_id"`
	PeriodType string      `json:"period_type"`
	TokenLimit pgtype.Int8 `json:"token_limit"`
	CostLimit  string      `json:"cost_limit"`
	Enabled    bool        `json:"enabled"`
}

func (q *Queries) GetQuotaPolicy(ctx context.Context, id int64) (GetQuotaPolicyRow, error) {
	row := q.db.QueryRow(ctx, getQuotaPolicy, id)
	var i GetQuotaPolicyRow
	err := row.Scan(
		&i.ID,
		&i.PolicyName,
		&i.ScopeType,
		&i.UserID,
		&i.ApiKeyID,
		&i.PeriodType,
		&i.TokenLimit,
		&i.CostLimit,
		&i.Enabled,
	)
	return i, err
}

const updateQuotaPolicy = `-- name: UpdateQuotaPolicy :execrows
UPDATE quota_policies
SET policy_name = $1, token_limit = $2,
    cost_limit = $3, enabled = $4, updated_at = now()
WHERE id = $5 AND deleted_at IS NULL
`

type UpdateQuotaPolicyParams struct {
	PolicyName string         `json:"policy_name"`
	TokenLimit pgtype.Int8    `json:"token_limit"`
	CostLimit  pgtype.Numeric `json:"cost_limit"`
	Enabled    bool           `json:"enabled"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateQuotaPolicy(ctx context.Context, arg UpdateQuotaPolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateQuotaPolicy,
		arg.PolicyName,
		arg.TokenLimit,
		arg.CostLimit,
		arg.Enabled,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
