// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateUsageByAPIKey = `-- name: AggregateUsageByAPIKey :many
SELECT api_key_id, count(*)::bigint AS request_count, count(*) FILTER (WHERE status = 'success')::bigint AS success_count, count(*) FILTER (WHERE status <> 'success')::bigint AS error_count, coalesce(sum(total_tokens), 0)::bigint AS total_tokens, coalesce(sum(total_cost), 0)::numeric(20, 6)::text AS total_cost, coalesce(sum(duration_ms), 0)::bigint AS duration_ms, count(*) OVER()::bigint AS aggregate_total
FROM usage_logs
WHERE created_at >= $1::timestamptz AND created_at < $2::timestamptz
  AND ($3::bigint IS NULL OR user_id = $3::bigint) AND ($4::bigint IS NULL OR api_key_id = $4::bigint) AND ($5::bigint IS NULL OR channel_id = $5::bigint) AND ($6::text IS NULL OR model = $6::text) AND ($7::text IS NULL OR status = $7::text)
GROUP BY api_key_id ORDER BY request_count DESC, api_key_id NULLS LAST LIMIT $9 OFFSET $8
`

type AggregateUsageByAPIKeyParams struct {
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	UserID     pgtype.Int8        `json:"user_id"`
	ApiKeyID   pgtype.Int8        `json:"api_key_id"`
	ChannelID  pgtype.Int8        `json:"channel_id"`
	Model      pgtype.Text        `json:"model"`
	Status     pgtype.Text        `json:"status"`
	PageOffset int32              `json:"page_offset"`
	PageLimit  int32              `json:"page_limit"`
}

type AggregateUsageByAPIKeyRow struct {
	ApiKeyID       pgtype.Int8 `json:"api_key_id"`
	RequestCount   int64       `json:"request_count"`
	SuccessCount   int64       `json:"success_count"`
	ErrorCount     int64       `json:"error_count"`
	TotalTokens    int64       `json:"total_tokens"`
	TotalCost      string      `json:"total_cost"`
	DurationMs     int64       `json:"duration_ms"`
	AggregateTotal int64       `json:"aggregate_total"`
}

func (q *Queries) AggregateUsageByAPIKey(ctx context.Context, arg AggregateUsageByAPIKeyParams) ([]AggregateUsageByAPIKeyRow, error) {
	rows, err := q.db.Query(ctx, aggregateUsageByAPIKey,
		arg.StartTime,
		arg.EndTime,
		arg.UserID,
		arg.ApiKeyID,
		arg.ChannelID,
		arg.Model,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateUsageByAPIKeyRow{}
	for rows.Next() {
		var i AggregateUsageByAPIKeyRow
		if err := rows.Scan(
			&i.ApiKeyID,
			&i.RequestCount,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.TotalTokens,
			&i.TotalCost,
			&i.DurationMs,
			&i.AggregateTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateUsageByChannel = `-- name: AggregateUsageByChannel :many
SELECT channel_id, count(*)::bigint AS request_count, count(*) FILTER (WHERE status = 'success')::bigint AS success_count, count(*) FILTER (WHERE status <> 'success')::bigint AS error_count, coalesce(sum(total_tokens), 0)::bigint AS total_tokens, coalesce(sum(total_cost), 0)::numeric(20, 6)::text AS total_cost, coalesce(sum(duration_ms), 0)::bigint AS duration_ms, count(*) OVER()::bigint AS aggregate_total
FROM usage_logs
WHERE created_at >= $1::timestamptz AND created_at < $2::timestamptz
  AND ($3::bigint IS NULL OR user_id = $3::bigint) AND ($4::bigint IS NULL OR api_key_id = $4::bigint) AND ($5::bigint IS NULL OR channel_id = $5::bigint) AND ($6::text IS NULL OR model = $6::text) AND ($7::text IS NULL OR status = $7::text)
GROUP BY channel_id ORDER BY request_count DESC, channel_id NULLS LAST LIMIT $9 OFFSET $8
`

type AggregateUsageByChannelParams struct {
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	UserID     pgtype.Int8        `json:"user_id"`
	ApiKeyID   pgtype.Int8        `json:"api_key_id"`
	ChannelID  pgtype.Int8        `json:"channel_id"`
	Model      pgtype.Text        `json:"model"`
	Status     pgtype.Text        `json:"status"`
	PageOffset int32              `json:"page_offset"`
	PageLimit  int32              `json:"page_limit"`
}

type AggregateUsageByChannelRow struct {
	ChannelID      pgtype.Int8 `json:"channel_id"`
	RequestCount   int64       `json:"request_count"`
	SuccessCount   int64       `json:"success_count"`
	ErrorCount     int64       `json:"error_count"`
	TotalTokens    int64       `json:"total_tokens"`
	TotalCost      string      `json:"total_cost"`
	DurationMs     int64       `json:"duration_ms"`
	AggregateTotal int64       `json:"aggregate_total"`
}

func (q *Queries) AggregateUsageByChannel(ctx context.Context, arg AggregateUsageByChannelParams) ([]AggregateUsageByChannelRow, error) {
	rows, err := q.db.Query(ctx, aggregateUsageByChannel,
		arg.StartTime,
		arg.EndTime,
		arg.UserID,
		arg.ApiKeyID,
		arg.ChannelID,
		arg.Model,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateUsageByChannelRow{}
	for rows.Next() {
		var i AggregateUsageByChannelRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.RequestCount,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.TotalTokens,
			&i.TotalCost,
			&i.DurationMs,
			&i.AggregateTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateUsageByModel = `-- name: AggregateUsageByModel :many
SELECT model, count(*)::bigint AS request_count, count(*) FILTER (WHERE status = 'success')::bigint AS success_count, count(*) FILTER (WHERE status <> 'success')::bigint AS error_count, coalesce(sum(total_tokens), 0)::bigint AS total_tokens, coalesce(sum(total_cost), 0)::numeric(20, 6)::text AS total_cost, coalesce(sum(duration_ms), 0)::bigint AS duration_ms, count(*) OVER()::bigint AS aggregate_total
FROM usage_logs
WHERE created_at >= $1::timestamptz AND created_at < $2::timestamptz
  AND ($3::bigint IS NULL OR user_id = $3::bigint) AND ($4::bigint IS NULL OR api_key_id = $4::bigint) AND ($5::bigint IS NULL OR channel_id = $5::bigint) AND ($6::text IS NULL OR model = $6::text) AND ($7::text IS NULL OR status = $7::text)
GROUP BY model ORDER BY request_count DESC, model LIMIT $9 OFFSET $8
`

type AggregateUsageByModelParams struct {
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	UserID     pgtype.Int8        `json:"user_id"`
	ApiKeyID   pgtype.Int8        `json:"api_key_id"`
	ChannelID  pgtype.Int8        `json:"channel_id"`
	Model      pgtype.Text        `json:"model"`
	Status     pgtype.Text        `json:"status"`
	PageOffset int32              `json:"page_offset"`
	PageLimit  int32              `json:"page_limit"`
}

type AggregateUsageByModelRow struct {
	Model          string `json:"model"`
	RequestCount   int64  `json:"request_count"`
	SuccessCount   int64  `json:"success_count"`
	ErrorCount     int64  `json:"error_count"`
	TotalTokens    int64  `json:"total_tokens"`
	TotalCost      string `json:"total_cost"`
	DurationMs     int64  `json:"duration_ms"`
	AggregateTotal int64  `json:"aggregate_total"`
}

func (q *Queries) AggregateUsageByModel(ctx context.Context, arg AggregateUsageByModelParams) ([]AggregateUsageByModelRow, error) {
	rows, err := q.db.Query(ctx, aggregateUsageByModel,
		arg.StartTime,
		arg.EndTime,
		arg.UserID,
		arg.ApiKeyID,
		arg.ChannelID,
		arg.Model,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateUsageByModelRow{}
	for rows.Next() {
		var i AggregateUsageByModelRow
		if err := rows.Scan(
			&i.Model,
			&i.RequestCount,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.TotalTokens,
			&i.TotalCost,
			&i.DurationMs,
			&i.AggregateTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateUsageByUser = `-- name: AggregateUsageByUser :many
SELECT user_id, count(*)::bigint AS request_count, count(*) FILTER (WHERE status = 'success')::bigint AS success_count, count(*) FILTER (WHERE status <> 'success')::bigint AS error_count, coalesce(sum(total_tokens), 0)::bigint AS total_tokens, coalesce(sum(total_cost), 0)::numeric(20, 6)::text AS total_cost, coalesce(sum(duration_ms), 0)::bigint AS duration_ms, count(*) OVER()::bigint AS aggregate_total
FROM usage_logs
WHERE created_at >= $1::timestamptz AND created_at < $2::timestamptz
  AND ($3::bigint IS NULL OR user_id = $3::bigint) AND ($4::bigint IS NULL OR api_key_id = $4::bigint) AND ($5::bigint IS NULL OR channel_id = $5::bigint) AND ($6::text IS NULL OR model = $6::text) AND ($7::text IS NULL OR status = $7::text)
GROUP BY user_id ORDER BY request_count DESC, user_id NULLS LAST LIMIT $9 OFFSET $8
`

type AggregateUsageByUserParams struct {
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	UserID     pgtype.Int8        `json:"user_id"`
	ApiKeyID   pgtype.Int8        `json:"api_key_id"`
	ChannelID  pgtype.Int8        `json:"channel_id"`
	Model      pgtype.Text        `json:"model"`
	Status     pgtype.Text        `json:"status"`
	PageOffset int32              `json:"page_offset"`
	PageLimit  int32              `json:"page_limit"`
}

type AggregateUsageByUserRow struct {
	UserID         pgtype.Int8 `json:"user_id"`
	RequestCount   int64       `json:"request_count"`
	SuccessCount   int64       `json:"success_count"`
	ErrorCount     int64       `json:"error_count"`
	TotalTokens    int64       `json:"total_tokens"`
	TotalCost      string      `json:"total_cost"`
	DurationMs     int64       `json:"duration_ms"`
	AggregateTotal int64       `json:"aggregate_total"`
}

func (q *Queries) AggregateUsageByUser(ctx context.Context, arg AggregateUsageByUserParams) ([]AggregateUsageByUserRow, error) {
	rows, err := q.db.Query(ctx, aggregateUsageByUser,
		arg.StartTime,
		arg.EndTime,
		arg.UserID,
		arg.ApiKeyID,
		arg.ChannelID,
		arg.Model,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateUsageByUserRow{}
	for rows.Next() {
		var i AggregateUsageByUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.RequestCount,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.TotalTokens,
			&i.TotalCost,
			&i.DurationMs,
			&i.AggregateTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRequestsSince = `-- name: CountRequestsSince :one
SELECT count(*)::int
FROM usage_logs
WHERE ($1 = 0 OR user_id = $1)
  AND created_at >= $2::timestamptz
  AND ($3::bigint IS NULL OR api_key_id = $3::bigint)
  AND ($4::text IS NULL OR model = $4::text)
  AND ($5::bigint IS NULL OR channel_id = $5::bigint)
`

type CountRequestsSinceParams struct {
	UserID    interface{}        `json:"user_id"`
	Since     pgtype.Timestamptz `json:"since"`
	ApiKeyID  pgtype.Int8        `json:"api_key_id"`
	Model     pgtype.Text        `json:"model"`
	ChannelID pgtype.Int8        `json:"channel_id"`
}

func (q *Queries) CountRequestsSince(ctx context.Context, arg CountRequestsSinceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRequestsSince,
		arg.UserID,
		arg.Since,
		arg.ApiKeyID,
		arg.Model,
		arg.ChannelID,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countStatsDaily = `-- name: CountStatsDaily :one
SELECT count(*)::int FROM (
    SELECT (l.created_at AT TIME ZONE 'UTC')::date AS stat_date
    FROM usage_logs l
    WHERE (l.created_at AT TIME ZONE 'UTC')::date >= $1::text::date
      AND (l.created_at AT TIME ZONE 'UTC')::date <= $2::text::date
    GROUP BY stat_date
) AS days
`

type CountStatsDailyParams struct {
	DateFrom string `json:"date_from"`
	DateTo   string `json:"date_to"`
}

func (q *Queries) CountStatsDaily(ctx context.Context, arg CountStatsDailyParams) (int32, error) {
	row := q.db.QueryRow(ctx, countStatsDaily, arg.DateFrom, arg.DateTo)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUsageLogs = `-- name: CountUsageLogs :one
SELECT count(*)::int
FROM usage_logs l
WHERE ($1::bigint IS NULL OR l.user_id = $1::bigint)
  AND ($2::bigint IS NULL OR l.api_key_id = $2::bigint)
  AND ($3::bigint IS NULL OR l.channel_id = $3::bigint)
  AND ($4::text IS NULL OR l.model = $4::text)
  AND ($5::text IS NULL OR l.status = $5::text)
  AND ($6::timestamptz IS NULL OR l.created_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR l.created_at <= $7::timestamptz)
`

type CountUsageLogsParams struct {
	UserID    pgtype.Int8        `json:"user_id"`
	ApiKeyID  pgtype.Int8        `json:"api_key_id"`
	ChannelID pgtype.Int8        `json:"channel_id"`
	Model     pgtype.Text        `json:"model"`
	Status    pgtype.Text        `json:"status"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) CountUsageLogs(ctx context.Context, arg CountUsageLogsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUsageLogs,
		arg.UserID,
		arg.ApiKeyID,
		arg.ChannelID,
		arg.Model,
		arg.Status,
		arg.StartTime,
		arg.EndTime,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getUsageLog = `-- name: GetUsageLog :one
SELECT
    l.id,
    l.request_id,
    l.user_id,
    l.api_key_id,
    l.channel_id,
    c.name AS channel_name,
    l.model,
    l.upstream_model,
    l.input_tokens,
    l.output_tokens,
    l.cached_input_tokens,
    l.total_tokens,
    l.unit_price_input_per_1m::text AS unit_price_input_per_1m,
    l.unit_price_output_per_1m::text AS unit_price_output_per_1m,
    l.total_cost::text AS total_cost,
    l.duration_ms,
    l.ttft_ms,
    l.status,
    l.error_code,
    l.client_ip,
    l.created_at
FROM usage_logs l
LEFT JOIN channels c ON c.id = l.channel_id
WHERE l.id = $1
`

type GetUsageLogRow struct {
	ID                   int64              `json:"id"`
	RequestID            string             `json:"request_id"`
	UserID               pgtype.Int8        `json:"user_id"`
	ApiKeyID             pgtype.Int8        `json:"api_key_id"`
	ChannelID            pgtype.Int8        `json:"channel_id"`
	ChannelName          pgtype.Text        `json:"channel_name"`
	Model                string             `json:"model"`
	UpstreamModel        string             `json:"upstream_model"`
	InputTokens          int64              `json:"input_tokens"`
	OutputTokens         int64              `json:"output_tokens"`
	CachedInputTokens    int64              `json:"cached_input_tokens"`
	TotalTokens          int64              `json:"total_tokens"`
	UnitPriceInputPer1m  string             `json:"unit_price_input_per_1m"`
	UnitPriceOutputPer1m string             `json:"unit_price_output_per_1m"`
	TotalCost            string             `json:"total_cost"`
	DurationMs           int64              `json:"duration_ms"`
	TtftMs               pgtype.Int8        `json:"ttft_ms"`
	Status               string             `json:"status"`
	ErrorCode            string             `json:"error_code"`
	ClientIp             string             `json:"client_ip"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUsageLog(ctx context.Context, id int64) (GetUsageLogRow, error) {
	row := q.db.QueryRow(ctx, getUsageLog, id)
	var i GetUsageLogRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.ChannelID,
		&i.ChannelName,
		&i.Model,
		&i.UpstreamModel,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedInputTokens,
		&i.TotalTokens,
		&i.UnitPriceInputPer1m,
		&i.UnitPriceOutputPer1m,
		&i.TotalCost,
		&i.DurationMs,
		&i.TtftMs,
		&i.Status,
		&i.ErrorCode,
		&i.ClientIp,
		&i.CreatedAt,
	)
	return i, err
}

const insertUsageLog = `-- name: InsertUsageLog :one
INSERT INTO usage_logs (
    request_id, user_id, api_key_id, channel_id, model, upstream_model,
    input_tokens, output_tokens, cached_input_tokens, total_tokens,
    unit_price_input_per_1m, unit_price_output_per_1m, total_cost,
    duration_ms, ttft_ms, status, error_code, client_ip
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    COALESCE(NULLIF($11, '')::numeric, 0),
    COALESCE(NULLIF($12, '')::numeric, 0),
    COALESCE(NULLIF($13, '')::numeric, 0),
    $14,
    $15,
    $16,
    $17,
    $18
)
RETURNING id
`

type InsertUsageLogParams struct {
	RequestID            string      `json:"request_id"`
	UserID               pgtype.Int8 `json:"user_id"`
	ApiKeyID             pgtype.Int8 `json:"api_key_id"`
	ChannelID            pgtype.Int8 `json:"channel_id"`
	Model                string      `json:"model"`
	UpstreamModel        string      `json:"upstream_model"`
	InputTokens          int64       `json:"input_tokens"`
	OutputTokens         int64       `json:"output_tokens"`
	CachedInputTokens    int64       `json:"cached_input_tokens"`
	TotalTokens          int64       `json:"total_tokens"`
	UnitPriceInputPer1m  interface{} `json:"unit_price_input_per_1m"`
	UnitPriceOutputPer1m interface{} `json:"unit_price_output_per_1m"`
	TotalCost            interface{} `json:"total_cost"`
	DurationMs           int64       `json:"duration_ms"`
	TtftMs               pgtype.Int8 `json:"ttft_ms"`
	Status               string      `json:"status"`
	ErrorCode            string      `json:"error_code"`
	ClientIp             string      `json:"client_ip"`
}

func (q *Queries) InsertUsageLog(ctx context.Context, arg InsertUsageLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertUsageLog,
		arg.RequestID,
		arg.UserID,
		arg.ApiKeyID,
		arg.ChannelID,
		arg.Model,
		arg.UpstreamModel,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedInputTokens,
		arg.TotalTokens,
		arg.UnitPriceInputPer1m,
		arg.UnitPriceOutputPer1m,
		arg.TotalCost,
		arg.DurationMs,
		arg.TtftMs,
		arg.Status,
		arg.ErrorCode,
		arg.ClientIp,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listUsageLogs = `-- name: ListUsageLogs :many
SELECT
    l.id,
    l.request_id,
    l.user_id,
    l.api_key_id,
    l.channel_id,
    c.name AS channel_name,
    l.model,
    l.upstream_model,
    l.input_tokens,
    l.output_tokens,
    l.cached_input_tokens,
    l.total_tokens,
    l.unit_price_input_per_1m::text AS unit_price_input_per_1m,
    l.unit_price_output_per_1m::text AS unit_price_output_per_1m,
    l.total_cost::text AS total_cost,
    l.duration_ms,
    l.ttft_ms,
    l.status,
    l.error_code,
    l.client_ip,
    l.created_at
FROM usage_logs l
LEFT JOIN channels c ON c.id = l.channel_id
WHERE ($1::bigint IS NULL OR l.user_id = $1::bigint)
  AND ($2::bigint IS NULL OR l.api_key_id = $2::bigint)
  AND ($3::bigint IS NULL OR l.channel_id = $3::bigint)
  AND ($4::text IS NULL OR l.model = $4::text)
  AND ($5::text IS NULL OR l.status = $5::text)
  AND ($6::timestamptz IS NULL OR l.created_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR l.created_at <= $7::timestamptz)
ORDER BY l.created_at DESC, l.id DESC
LIMIT $9 OFFSET $8
`

type ListUsageLogsParams struct {
	UserID     pgtype.Int8        `json:"user_id"`
	ApiKeyID   pgtype.Int8        `json:"api_key_id"`
	ChannelID  pgtype.Int8        `json:"channel_id"`
	Model      pgtype.Text        `json:"model"`
	Status     pgtype.Text        `json:"status"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	PageOffset int32              `json:"page_offset"`
	PageLimit  int32              `json:"page_limit"`
}

type ListUsageLogsRow struct {
	ID                   int64              `json:"id"`
	RequestID            string             `json:"request_id"`
	UserID               pgtype.Int8        `json:"user_id"`
	ApiKeyID             pgtype.Int8        `json:"api_key_id"`
	ChannelID            pgtype.Int8        `json:"channel_id"`
	ChannelName          pgtype.Text        `json:"channel_name"`
	Model                string             `json:"model"`
	UpstreamModel        string             `json:"upstream_model"`
	InputTokens          int64              `json:"input_tokens"`
	OutputTokens         int64              `json:"output_tokens"`
	CachedInputTokens    int64              `json:"cached_input_tokens"`
	TotalTokens          int64              `json:"total_tokens"`
	UnitPriceInputPer1m  string             `json:"unit_price_input_per_1m"`
	UnitPriceOutputPer1m string             `json:"unit_price_output_per_1m"`
	TotalCost            string             `json:"total_cost"`
	DurationMs           int64              `json:"duration_ms"`
	TtftMs               pgtype.Int8        `json:"ttft_ms"`
	Status               string             `json:"status"`
	ErrorCode            string             `json:"error_code"`
	ClientIp             string             `json:"client_ip"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsageLogs(ctx context.Context, arg ListUsageLogsParams) ([]ListUsageLogsRow, error) {
	rows, err := q.db.Query(ctx, listUsageLogs,
		arg.UserID,
		arg.ApiKeyID,
		arg.ChannelID,
		arg.Model,
		arg.Status,
		arg.StartTime,
		arg.EndTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsageLogsRow{}
	for rows.Next() {
		var i ListUsageLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.UserID,
			&i.ApiKeyID,
			&i.ChannelID,
			&i.ChannelName,
			&i.Model,
			&i.UpstreamModel,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedInputTokens,
			&i.TotalTokens,
			&i.UnitPriceInputPer1m,
			&i.UnitPriceOutputPer1m,
			&i.TotalCost,
			&i.DurationMs,
			&i.TtftMs,
			&i.Status,
			&i.ErrorCode,
			&i.ClientIp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsChannels = `-- name: StatsChannels :many
SELECT
    l.channel_id,
    coalesce(c.name, '') AS channel_name,
    count(*)::bigint AS request_count,
    count(*) FILTER (WHERE l.status = 'success')::bigint AS success_count,
    count(*) FILTER (WHERE l.status <> 'success')::bigint AS error_count,
    coalesce(sum(l.total_tokens), 0)::bigint AS total_tokens,
    coalesce(sum(l.total_cost), 0)::numeric(20, 6)::text AS total_cost
FROM usage_logs l
LEFT JOIN channels c ON c.id = l.channel_id
WHERE l.created_at >= $1 AND l.created_at <= $2
GROUP BY l.channel_id, c.name
ORDER BY request_count DESC, l.channel_id
`

type StatsChannelsParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type StatsChannelsRow struct {
	ChannelID    pgtype.Int8 `json:"channel_id"`
	ChannelName  string      `json:"channel_name"`
	RequestCount int64       `json:"request_count"`
	SuccessCount int64       `json:"success_count"`
	ErrorCount   int64       `json:"error_count"`
	TotalTokens  int64       `json:"total_tokens"`
	TotalCost    string      `json:"total_cost"`
}

func (q *Queries) StatsChannels(ctx context.Context, arg StatsChannelsParams) ([]StatsChannelsRow, error) {
	rows, err := q.db.Query(ctx, statsChannels, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsChannelsRow{}
	for rows.Next() {
		var i StatsChannelsRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelName,
			&i.RequestCount,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.TotalTokens,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsDaily = `-- name: StatsDaily :many
SELECT
    (l.created_at AT TIME ZONE 'UTC')::date AS stat_date,
    count(*)::bigint AS request_count,
    count(*) FILTER (WHERE l.status = 'success')::bigint AS success_count,
    count(*) FILTER (WHERE l.status <> 'success')::bigint AS error_count,
    coalesce(sum(l.total_tokens), 0)::bigint AS total_tokens,
    coalesce(sum(l.total_cost), 0)::numeric(20, 6)::text AS total_cost
FROM usage_logs l
WHERE (l.created_at AT TIME ZONE 'UTC')::date >= $1::text::date
  AND (l.created_at AT TIME ZONE 'UTC')::date <= $2::text::date
GROUP BY stat_date
ORDER BY stat_date
LIMIT $4 OFFSET $3
`

type StatsDailyParams struct {
	DateFrom   string `json:"date_from"`
	DateTo     string `json:"date_to"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type StatsDailyRow struct {
	StatDate     pgtype.Date `json:"stat_date"`
	RequestCount int64       `json:"request_count"`
	SuccessCount int64       `json:"success_count"`
	ErrorCount   int64       `json:"error_count"`
	TotalTokens  int64       `json:"total_tokens"`
	TotalCost    string      `json:"total_cost"`
}

func (q *Queries) StatsDaily(ctx context.Context, arg StatsDailyParams) ([]StatsDailyRow, error) {
	rows, err := q.db.Query(ctx, statsDaily,
		arg.DateFrom,
		arg.DateTo,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsDailyRow{}
	for rows.Next() {
		var i StatsDailyRow
		if err := rows.Scan(
			&i.StatDate,
			&i.RequestCount,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.TotalTokens,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsOverview = `-- name: StatsOverview :one
SELECT
    count(*)::bigint AS request_count,
    count(*) FILTER (WHERE status = 'success')::bigint AS success_count,
    count(*) FILTER (WHERE status <> 'success')::bigint AS error_count,
    coalesce(sum(total_tokens), 0)::bigint AS total_tokens,
    coalesce(sum(total_cost), 0)::numeric(20, 6)::text AS total_cost,
    count(DISTINCT user_id)::bigint AS active_user_count
FROM usage_logs
WHERE created_at >= $1 AND created_at <= $2
`

type StatsOverviewParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type StatsOverviewRow struct {
	RequestCount    int64  `json:"request_count"`
	SuccessCount    int64  `json:"success_count"`
	ErrorCount      int64  `json:"error_count"`
	TotalTokens     int64  `json:"total_tokens"`
	TotalCost       string `json:"total_cost"`
	ActiveUserCount int64  `json:"active_user_count"`
}

func (q *Queries) StatsOverview(ctx context.Context, arg StatsOverviewParams) (StatsOverviewRow, error) {
	row := q.db.QueryRow(ctx, statsOverview, arg.CreatedAt, arg.CreatedAt_2)
	var i StatsOverviewRow
	err := row.Scan(
		&i.RequestCount,
		&i.SuccessCount,
		&i.ErrorCount,
		&i.TotalTokens,
		&i.TotalCost,
		&i.ActiveUserCount,
	)
	return i, err
}

const statsTTFT = `-- name: StatsTTFT :one
SELECT
    count(*)::bigint AS sample_count,
    coalesce(floor(avg(ttft_ms))::bigint, 0)::bigint AS average_ms,
    coalesce(percentile_disc(0.50) WITHIN GROUP (ORDER BY ttft_ms), 0)::bigint AS p50_ms,
    coalesce(percentile_disc(0.95) WITHIN GROUP (ORDER BY ttft_ms), 0)::bigint AS p95_ms,
    coalesce(percentile_disc(0.99) WITHIN GROUP (ORDER BY ttft_ms), 0)::bigint AS p99_ms
FROM usage_logs
WHERE ttft_ms IS NOT NULL
  AND ($1::bigint IS NULL OR user_id = $1::bigint)
  AND ($2::bigint IS NULL OR api_key_id = $2::bigint)
  AND ($3::bigint IS NULL OR channel_id = $3::bigint)
  AND ($4::text IS NULL OR model = $4::text)
  AND created_at >= $5::timestamptz
  AND created_at <= $6::timestamptz
`

type StatsTTFTParams struct {
	UserID    pgtype.Int8        `json:"user_id"`
	ApiKeyID  pgtype.Int8        `json:"api_key_id"`
	ChannelID pgtype.Int8        `json:"channel_id"`
	Model     pgtype.Text        `json:"model"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type StatsTTFTRow struct {
	SampleCount int64 `json:"sample_count"`
	AverageMs   int64 `json:"average_ms"`
	P50Ms       int64 `json:"p50_ms"`
	P95Ms       int64 `json:"p95_ms"`
	P99Ms       int64 `json:"p99_ms"`
}

func (q *Queries) StatsTTFT(ctx context.Context, arg StatsTTFTParams) (StatsTTFTRow, error) {
	row := q.db.QueryRow(ctx, statsTTFT,
		arg.UserID,
		arg.ApiKeyID,
		arg.ChannelID,
		arg.Model,
		arg.StartTime,
		arg.EndTime,
	)
	var i StatsTTFTRow
	err := row.Scan(
		&i.SampleCount,
		&i.AverageMs,
		&i.P50Ms,
		&i.P95Ms,
		&i.P99Ms,
	)
	return i, err
}
